// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"

	"fyne.io/fyne/v2"
)

//go:embed assets/images/KrankyBearBeret.png
var resourceKrankyBearBeretPngData []byte
var resourceKrankyBearBeretPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearBeret.png",
	StaticContent: resourceKrankyBearBeretPngData,
}

//go:embed assets/images/KrankyBearCowboyBrown.png
var resourceKrankyBearCowboyBrownPngData []byte
var resourceKrankyBearCowboyBrownPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearCowboyBrown.png",
	StaticContent: resourceKrankyBearCowboyBrownPngData,
}

//go:embed assets/images/KrankyBearChristmasGrinch.png
var resourceKrankyBearChristmasGrinchPngData []byte
var resourceKrankyBearChristmasGrinchPng = &fyne.StaticResource{
	StaticName:    "assets/images/KrankyBearChristmasGrinch.png",
	StaticContent: resourceKrankyBearChristmasGrinchPngData,
}
